#!/bin/bash

# install.sh --- Install spacemacs

# Backup a file/directory by renaming it with the current date and time
function backup_file {
	local file=$1
	local file_ext=$(date +%Y%m%d%H%M)

	if [ -e ${file} ]; then
		if ! [ -h ${file} ]; then
			echo "Backing up ${file} to: ${file}.${file_ext}"
			mv ${file} ${file}.${file_ext}
		fi
	fi
}

# create a symbolic link if one does not allready exist
function link_file {
    local src=$1
    local dst=$2

    if ! [ -e ${dst} ]; then
        echo "Linking file ${dst}"
        ln -sfnv ${src} ${dst}
    fi
}

SCRIPT_PATH=$( cd "$(dirname "$BASH_SOURCE")" ; pwd -P )
pushd "$SCRIPT_PATH" > /dev/null

# Backup existing spacemacs.d directory
backup_file "${HOME}/.spacemacs.d"

# Create a symbolic link in the home directory to the spacemacs.d directory
link_file "${SCRIPT_PATH}/spacemacs.d" "${HOME}/.spacemacs.d" 

# Backup existing .eamcs file and/or .emacs.d directory
backup_file "${HOME}/.emacs"
backup_file "${HOME}/.emacs.d"

# Clone the official spacemacs repo into emacs.d
if ! [ -e "${SCRIPT_PATH}/.emacs.d" ]; then
	git clone https://github.com/syl20bnr/spacemacs ${SCRIPT_PATH}/.emacs.d
fi

# Create a symolic link in the home directory to the emacs.d directory
link_file "${SCRIPT_PATH}/.emacs.d" "${HOME}/.emacs.d" 

popd > /dev/null
