#!/bin/bash

# install.sh --- Install spacemacs

# Backup a file/directory by renaming it with the current date and time
function backup_file {
	local file=$1
	local backup=$(date +%Y%m%d%H%M)

	if [ -e ${file} ]; then
		if ! [ -h ${file} ]; then
			echo "Backing up ${file} to: ${file}.${backup}"
			mv ${file} ${file}.${backup}
		fi
	fi
}

script_path=$( cd "$(dirname "$BASH_SOURCE")" ; pwd -P )
file="spacemacs.d"

# Backup existing spacemacs.d directory
backup_file "${HOME}/.spacemacs.d"

# Create a symbolic link in the home directory to the spacemacs.d directory
ln -fsnv "${script_path}/spacemacs.d" "${HOME}/.spacemacs.d" 

# Backup existing .eamcs file and/or .emacs.d directory
backup_file "${HOME}/.emacs"
backup_file "${HOME}/.emacs.d"

# Clone the official spacemacs repo into emacs.d
if ! [ -e "${script_path}/emacs.d" ]; then
	git clone https://github.com/syl20bnr/spacemacs ${script_path}/emacs.d
fi

# Create a symolic link in the home directory to the emacs.d directory
ln -fsnv "${script_path}/emacs.d" "${HOME}/.emacs.d" 

# Spacemacs setup, tell the user where the spacemacs configuration is located.
echo ""
echo "Congratulation, Spacemacs is now setup."
echo "You edit your personal configuration located in the file:"
echo "${HOME}./.spacemacs.d/init.d"
echo ""
